FROM cwds/javajdk
RUN mkdir /opt/cwds-perry
RUN mkdir /opt/cwds-perry/logs
ADD config/* /opt/cwds-perry/config/
ADD entrypoint.sh /opt/cwds-perry/
ADD libs/${perry_dist_file_name} /opt/cwds-perry/perry.jar
EXPOSE 8080
EXPOSE 9082
RUN chmod +x /opt/cwds-perry/entrypoint.sh
WORKDIR /opt/cwds-perry
CMD ["/opt/cwds-perry/entrypoint.sh"]
