/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CWS-NS3' at '12/21/16 9:05 AM' with Gradle 2.14.1
 *
 * @author CWS-NS3, @date 12/21/16 9:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
